"""Integrated reconstruction pipeline public helpers."""

from .projection import (
    DensityMap,
    PlanBounds,
    WallBand,
    project_top_down_density,
    project_wall_density,
    rasterize_points,
)
from .planes import (
    FINISHED_FACE,
    ProjectedWallLine,
    WallCoordinateConvention,
    project_vertical_plane,
    vertical_plane_to_line,
)
from .wall_graph import (
    ConnectionType,
    WallGraph,
    WallGraphConnection,
    WallGraphDiagnostics,
    WallGraphNode,
    solve_wall_graph,
)
from .roomformer import (
    TENSOR_CHANNELS,
    RoomFormerCoordinateSpace,
    RoomFormerAdapter,
    RoomFormerConfig,
    RoomFormerPrediction,
    RoomFormerProposal,
    RoomFormerTensor,
    WallGraphProposal,
    build_roomformer_tensor,
)
from .vectorizer import (
    AdjacencyEvidence,
    FaceEvidence,
    OpeningEvidence,
    VectorizerInput,
    VectorizerOutput,
    build_vectorizer_input,
    build_vectorizer_output,
)

__all__ = [
    "DensityMap",
    "PlanBounds",
    "WallBand",
    "project_top_down_density",
    "project_wall_density",
    "rasterize_points",
    "FINISHED_FACE",
    "ProjectedWallLine",
    "WallCoordinateConvention",
    "vertical_plane_to_line",
    "project_vertical_plane",
    "WallGraph",
    "ConnectionType",
    "WallGraphDiagnostics",
    "WallGraphConnection",
    "WallGraphNode",
    "solve_wall_graph",
    "RoomFormerAdapter",
    "RoomFormerCoordinateSpace",
    "RoomFormerConfig",
    "RoomFormerPrediction",
    "RoomFormerProposal",
    "RoomFormerTensor",
    "WallGraphProposal",
    "build_roomformer_tensor",
    "TENSOR_CHANNELS",
    "AdjacencyEvidence",
    "FaceEvidence",
    "OpeningEvidence",
    "VectorizerInput",
    "VectorizerOutput",
    "build_vectorizer_input",
    "build_vectorizer_output",
]
